/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAffirmationsRouteImport } from './routes/_authenticated/app.affirmations'
import { Route as AuthenticatedAppCoachRouteImport } from './routes/_authenticated/app.coach'
import { Route as AuthenticatedAppGoalsRouteImport } from './routes/_authenticated/app.goals'
import { Route as AuthenticatedAppHabitsRouteImport } from './routes/_authenticated/app.habits'
import { Route as AuthenticatedAppJournalRouteImport } from './routes/_authenticated/app.journal'
import { Route as AuthenticatedAppLibraryRouteImport } from './routes/_authenticated/app.library'
import { Route as AuthenticatedAppMomentsRouteImport } from './routes/_authenticated/app.moments'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppProgressRouteImport } from './routes/_authenticated/app.progress'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppGoalsIndexRouteImport } from './routes/_authenticated/app.goals.index'
import { Route as AuthenticatedAppGoalsGoalIdRouteImport } from './routes/_authenticated/app.goals.$goalId'
import { Route as AuthenticatedAppStoryStoryIdRouteImport } from './routes/_authenticated/app.story.$storyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAffirmationsRoute =
  AuthenticatedAppAffirmationsRouteImport.update({
    id: '/affirmations',
    path: '/affirmations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCoachRoute = AuthenticatedAppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGoalsRoute = AuthenticatedAppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHabitsRoute = AuthenticatedAppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppJournalRoute = AuthenticatedAppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLibraryRoute = AuthenticatedAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMomentsRoute = AuthenticatedAppMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProgressRoute =
  AuthenticatedAppProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGoalsIndexRoute =
  AuthenticatedAppGoalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppGoalsRoute,
  } as any)
const AuthenticatedAppGoalsGoalIdRoute =
  AuthenticatedAppGoalsGoalIdRouteImport.update({
    id: '/$goalId',
    path: '/$goalId',
    getParentRoute: () => AuthenticatedAppGoalsRoute,
  } as any)
const AuthenticatedAppStoryStoryIdRoute =
  AuthenticatedAppStoryStoryIdRouteImport.update({
    id: '/story/$storyId',
    path: '/story/$storyId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/affirmations': typeof AuthenticatedAppAffirmationsRoute
  '/app/coach': typeof AuthenticatedAppCoachRoute
  '/app/goals': typeof AuthenticatedAppGoalsRouteWithChildren
  '/app/habits': typeof AuthenticatedAppHabitsRoute
  '/app/journal': typeof AuthenticatedAppJournalRoute
  '/app/library': typeof AuthenticatedAppLibraryRoute
  '/app/moments': typeof AuthenticatedAppMomentsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/goals/$goalId': typeof AuthenticatedAppGoalsGoalIdRoute
  '/app/story/$storyId': typeof AuthenticatedAppStoryStoryIdRoute
  '/app/goals/': typeof AuthenticatedAppGoalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/affirmations': typeof AuthenticatedAppAffirmationsRoute
  '/app/coach': typeof AuthenticatedAppCoachRoute
  '/app/habits': typeof AuthenticatedAppHabitsRoute
  '/app/journal': typeof AuthenticatedAppJournalRoute
  '/app/library': typeof AuthenticatedAppLibraryRoute
  '/app/moments': typeof AuthenticatedAppMomentsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/goals/$goalId': typeof AuthenticatedAppGoalsGoalIdRoute
  '/app/story/$storyId': typeof AuthenticatedAppStoryStoryIdRoute
  '/app/goals': typeof AuthenticatedAppGoalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/affirmations': typeof AuthenticatedAppAffirmationsRoute
  '/_authenticated/app/coach': typeof AuthenticatedAppCoachRoute
  '/_authenticated/app/goals': typeof AuthenticatedAppGoalsRouteWithChildren
  '/_authenticated/app/habits': typeof AuthenticatedAppHabitsRoute
  '/_authenticated/app/journal': typeof AuthenticatedAppJournalRoute
  '/_authenticated/app/library': typeof AuthenticatedAppLibraryRoute
  '/_authenticated/app/moments': typeof AuthenticatedAppMomentsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/progress': typeof AuthenticatedAppProgressRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/goals/$goalId': typeof AuthenticatedAppGoalsGoalIdRoute
  '/_authenticated/app/story/$storyId': typeof AuthenticatedAppStoryStoryIdRoute
  '/_authenticated/app/goals/': typeof AuthenticatedAppGoalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/app'
    | '/onboarding'
    | '/app/affirmations'
    | '/app/coach'
    | '/app/goals'
    | '/app/habits'
    | '/app/journal'
    | '/app/library'
    | '/app/moments'
    | '/app/profile'
    | '/app/progress'
    | '/app/settings'
    | '/app/'
    | '/app/goals/$goalId'
    | '/app/story/$storyId'
    | '/app/goals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/onboarding'
    | '/app/affirmations'
    | '/app/coach'
    | '/app/habits'
    | '/app/journal'
    | '/app/library'
    | '/app/moments'
    | '/app/profile'
    | '/app/progress'
    | '/app/settings'
    | '/app'
    | '/app/goals/$goalId'
    | '/app/story/$storyId'
    | '/app/goals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/affirmations'
    | '/_authenticated/app/coach'
    | '/_authenticated/app/goals'
    | '/_authenticated/app/habits'
    | '/_authenticated/app/journal'
    | '/_authenticated/app/library'
    | '/_authenticated/app/moments'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/progress'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/goals/$goalId'
    | '/_authenticated/app/story/$storyId'
    | '/_authenticated/app/goals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/affirmations': {
      id: '/_authenticated/app/affirmations'
      path: '/affirmations'
      fullPath: '/app/affirmations'
      preLoaderRoute: typeof AuthenticatedAppAffirmationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/coach': {
      id: '/_authenticated/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AuthenticatedAppCoachRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/goals': {
      id: '/_authenticated/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AuthenticatedAppGoalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/habits': {
      id: '/_authenticated/app/habits'
      path: '/habits'
      fullPath: '/app/habits'
      preLoaderRoute: typeof AuthenticatedAppHabitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/journal': {
      id: '/_authenticated/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AuthenticatedAppJournalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/library': {
      id: '/_authenticated/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AuthenticatedAppLibraryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/moments': {
      id: '/_authenticated/app/moments'
      path: '/moments'
      fullPath: '/app/moments'
      preLoaderRoute: typeof AuthenticatedAppMomentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/progress': {
      id: '/_authenticated/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AuthenticatedAppProgressRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/goals/': {
      id: '/_authenticated/app/goals/'
      path: '/'
      fullPath: '/app/goals/'
      preLoaderRoute: typeof AuthenticatedAppGoalsIndexRouteImport
      parentRoute: typeof AuthenticatedAppGoalsRoute
    }
    '/_authenticated/app/goals/$goalId': {
      id: '/_authenticated/app/goals/$goalId'
      path: '/$goalId'
      fullPath: '/app/goals/$goalId'
      preLoaderRoute: typeof AuthenticatedAppGoalsGoalIdRouteImport
      parentRoute: typeof AuthenticatedAppGoalsRoute
    }
    '/_authenticated/app/story/$storyId': {
      id: '/_authenticated/app/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/app/story/$storyId'
      preLoaderRoute: typeof AuthenticatedAppStoryStoryIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppGoalsRouteChildren {
  AuthenticatedAppGoalsGoalIdRoute: typeof AuthenticatedAppGoalsGoalIdRoute
  AuthenticatedAppGoalsIndexRoute: typeof AuthenticatedAppGoalsIndexRoute
}

const AuthenticatedAppGoalsRouteChildren: AuthenticatedAppGoalsRouteChildren = {
  AuthenticatedAppGoalsGoalIdRoute: AuthenticatedAppGoalsGoalIdRoute,
  AuthenticatedAppGoalsIndexRoute: AuthenticatedAppGoalsIndexRoute,
}

const AuthenticatedAppGoalsRouteWithChildren =
  AuthenticatedAppGoalsRoute._addFileChildren(
    AuthenticatedAppGoalsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAffirmationsRoute: typeof AuthenticatedAppAffirmationsRoute
  AuthenticatedAppCoachRoute: typeof AuthenticatedAppCoachRoute
  AuthenticatedAppGoalsRoute: typeof AuthenticatedAppGoalsRouteWithChildren
  AuthenticatedAppHabitsRoute: typeof AuthenticatedAppHabitsRoute
  AuthenticatedAppJournalRoute: typeof AuthenticatedAppJournalRoute
  AuthenticatedAppLibraryRoute: typeof AuthenticatedAppLibraryRoute
  AuthenticatedAppMomentsRoute: typeof AuthenticatedAppMomentsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppProgressRoute: typeof AuthenticatedAppProgressRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppStoryStoryIdRoute: typeof AuthenticatedAppStoryStoryIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAffirmationsRoute: AuthenticatedAppAffirmationsRoute,
  AuthenticatedAppCoachRoute: AuthenticatedAppCoachRoute,
  AuthenticatedAppGoalsRoute: AuthenticatedAppGoalsRouteWithChildren,
  AuthenticatedAppHabitsRoute: AuthenticatedAppHabitsRoute,
  AuthenticatedAppJournalRoute: AuthenticatedAppJournalRoute,
  AuthenticatedAppLibraryRoute: AuthenticatedAppLibraryRoute,
  AuthenticatedAppMomentsRoute: AuthenticatedAppMomentsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppProgressRoute: AuthenticatedAppProgressRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppStoryStoryIdRoute: AuthenticatedAppStoryStoryIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
